name: Code Linters
on:
  - pull_request
  - workflow_dispatch

jobs:
  pronto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 10
      - run: |
          git fetch --no-tags --prune --depth=10 origin +refs/heads/*:refs/remotes/origin/*
      - uses: actions/setup-node@v6
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - run: npm install
      - name: Setup pronto
        run: gem install pronto pronto-rubocop
      - name: Lint JavaScript
        run: npm run lint
      - name: Run Pronto
        run: bundle exec pronto run -f github_combined_status github_pr_review -c origin/${{ github.base_ref }}
        env:
          PRONTO_PULL_REQUEST_ID: ${{ github.event.pull_request.number }}
          PRONTO_GITHUB_ACCESS_TOKEN: "${{ github.token }}"
